name: sccapppcopy
description: "A new Flutter project."

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Remove duplicate platform-specific packages
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  url_launcher: ^6.3.0
  # Keep only main packages, remove platform interfaces (they're auto-included)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/